### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by AndreyGalitsin** [UttaranB127/take_an_emotion_walk#3]
H Uttarani! 
Help me please, I want to create a demo script where to use a video from my camera as an input data for your model. I use a 3D human pose detector to get a skeleton points at first. But your model requires not only 21 3d points, but also 3 scalar control signals (forward, sideways and rotational velocity) for each frame. Tell me please, how can I get them? Or is it possible not to use this info inside your model?

**Comment by UttaranB127** [comment]
Hi Andrey,

I haven't computed these scalar points by hand for the Edinburgh dataset. But you can verify whether they match the definition and compute them accordingly:

Forward velocity at time step _t_: x_position of the root at _t_ - x_position of the root at _t-1_

Sideways velocity at time step _t_: z_position of the root at _t_ - z_position of the root at _t-1_

Rotational velocity at time step _t_: smaller angle between the root positions at _t_ and _t-1_. This can be computed as the inverse cosine of the corresponding normalized position vectors.

**Comment by AndreyGalitsin** [comment]
Thank you very much!
